### ISSUE TITLE
'autoprefixer' in gulpfile.js

### ISSUE THREAD

**Issue by timothyjensen** [KnowTheCode/Genesis-Developer-Starter-Lab#1]
~~I believe 'autoprefixer' in gulpfile.js should be changed to 'gulp-autoprefixer'.~~

Actually, the issue is in package.json, where 'gulp-autoprefixer' should be changed to 'autoprefixer'.

**Comment by hellofromtonya** [comment]
Hey Tim,

Thank you. Updated as you [can see here](<a href="https://www.npmjs.com/package/gulp-autoprefixer" target="_blank">autoprefixer package</a>) and made a note in [the episode](https://knowthecode.io/labs/part-3b-doing-more-gulp/episode-1) too.

**Comment by timothyjensen** [comment]
When using gulp-autoprefixer I still see the error `gulp-notify: [Task Failed [[object Object] is not a PostCSS plugin]`.  

Is the problem with this? : 
```
.pipe( postcss([
            autoprefixer({
                browsers: ['last 2 versions']
            })
        ]))
```

**Comment by hellofromtonya** [comment]
Whoops. We want to use the [PostCSS Autoprefixer](https://www.npmjs.com/package/autoprefixer) and not the `gulp-autoprefixer`.   Sorry about that.  The `package.json` now has the right autoprefixer in it.

To install on your machine, type:  `npm install --save-dev autoprefixer`
