### ISSUE TITLE
Refactoring Theme Supports

### ISSUE THREAD

**Issue by Herm71** [KnowTheCode/Genesis-Developer-Starter-Lab#3]
Hello, I am following along with this tutorial series. So far it's excellent! I've been a genesis developer for about five years and already I've learned a ton! My issue:

I downloaded the latest Genesis Sample theme -- the one with WooCommerce Support -- for use in this tutorial. I've configured my setup.php file with the `$config` array and the `foreach` loop, like the tutorial instructs. When I get to the point where we test it by pasting it into the Genesis Sample `functions.php` and comment out all the other `add_theme_support()` statements ... nothing happens. By which, I mean that I lose all the footer widget areas, after content widget area, etc. Additionally, on the front-end I loose all my styling.

My IDE did not register any syntax errors but, just to be safe, I copied the same code from your repo and pasted it into my `setup.php` and Genesis Sample's `functions.php` and tried again ... same behavior. 

Any suggestions? I attached a couple screenies to show what happens.

![screenshot from 2017-08-29 10-55-01](https://user-images.githubusercontent.com/1000543/29836120-1aec64ca-8ca9-11e7-8ea2-bb3820d93ca8.png)
![screenshot from 2017-08-29 10-55-46](https://user-images.githubusercontent.com/1000543/29836134-21a27732-8ca9-11e7-8300-56d8db53e1c3.png)

**Comment by hellofromtonya** [comment]
Hello @Herm71,

For support with the lab, go ahead and use the [Pro Forums](https://knowthecode.io/forums).  When you do, share a link to your project (GitHub, GitLab, BitBucket, or whatever) so that I can look at your code and better advice you to what is happening.

Cheers,
Tonya

**Comment by Herm71** [comment]
Hi, 
Thanks for the head's up. I'm new to your site, so I'll go post in the forums.
